pkgname = "model"
output = "model"
wipe = true
add-global-variants = false
no-tests = false

[psql]
  dbname  = "last-order"
  host    = "db"
  port    = 5432
  user    = "postgres"
  pass    = "postgres"
  sslmode = "disable"
  schema = "public"

[[types]]
  [types.match]
    tables = ["sisters"]
    name = "sister_id"
  [types.replace]
    type = "uuid.UUID"
  [types.imports]
    third_party = ['"github.com/google/uuid"']
