linters:
  enable-all: true
  disable:
    - deadcode
    - depguard
    - exhaustivestruct
    - golint
    - ifshort
    - interfacer
    - maligned
    - nosnakecase
    - scopelint
    - structcheck
    - varcheck
    - exhaustruct
    - forbidigo
    - testpackage
linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/radio-noise-project/last-order)
      - blank
      - dot
  varnamelen:
    ignore-decls:
      - e *echo.Echo
      - c echo.Context
  wrapcheck:
    ignoreSigs:
      - .JSON(
