services:
  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: last-order-api
    volumes:
      - .:/go/src/app
      - /var/run/docker.sock:/var/run/docker.sock
    hostname: api
    restart: always
    tty: true
    depends_on:
      - db
    ports:
      # REST API PORT
      - ${LASTORDER_PORT}:8080
      # GRPC PORT
      - ${LASTORDER_GRPC_PORT}:50051
    environment:
      TZ: ${POSTGRES_TIMEZONE}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: last-order-db
    restart: always
    tty: true
    ports:
      - ${POSTGRES_PORT}:5432
    hostname: db
    volumes:
      - db-store:/var/lib/postgresql/data
    environment:
      TZ: ${POSTGRES_TIMEZONE}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    networks:
      - lo-network

networks:
  lo-network:
    driver: bridge

volumes:
  db-store:
