version: '3'

services:

  api:
    build:
      context: .
      dockerfile: ./docker/api/Dockerfile
    container_name: last-order-api
    volumes:
      - ./cmd/last-order:/go/src/app/cmd/
      - ./pkg:/go/src/app/pkg/
      - ./internal:go/src/app/internal
    hostname: backend
    restart: always
    tty: true
    ports:
      - 8080:8080

  db:
    build:
      context: .
      dockerfile: ./docker/db/Dockerfile
    container_name: last-order-db
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./docker/db/init.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_USER: 'user'
      POSTGRES_PASSWORD: 'postgres'
    networks:
      - db-network

networks:
  db-network:
    driver: bridge

volumes:
  db-store:
