// Code generated by SQLBoiler 3.7.1 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package model

import "testing"

func TestUpsert(t *testing.T) {
	t.Run("Keys", testKeysUpsert)

	t.Run("SchemaMigrations", testSchemaMigrationsUpsert)

	t.Run("Sisters", testSistersUpsert)
}
